# Generated by Django 2.0.6 on 2018-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognitionWebsite', '0003_auto_20181122_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.CharField(default='opis', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.FloatField(),
        ),
    ]
