# Generated by Django 2.0.6 on 2018-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognitionWebsite', '0004_auto_20181122_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date'),
        ),
    ]
