# Generated by Django 2.0.6 on 2018-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognitionWebsite', '0007_auto_20181126_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='members_ids',
        ),
        migrations.AddField(
            model_name='attendance',
            name='members',
            field=models.ManyToManyField(to='faceRecognitionWebsite.Person', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(to='faceRecognitionWebsite.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(to='faceRecognitionWebsite.Group', verbose_name='groups'),
        ),
    ]
